### ISSUE TITLE
Используйте либо continue, либо else - иначе у вас все три проверки гоняются

### ISSUE THREAD

**Issue by coursar** [muhacc20/hometask#3]
https://github.com/muhacc20/hometask/blob/16b25cbdd4a2067d0c9db9390a5f0c435079cc20/src/js/app.js#L46-L55

**Comment by muhacc20** [comment]
if(purchase.category == REGULAR_CATEGORY)  { 
     predictCashback += purchase.amound * regularPurchasesPercent; 
 }  else  
 if (purchase.category == INCREASED_CATEGORY) { 
     predictCashback += purchase.amound * increasedPurchasesPercent; 
 }  else
 if (purchase.category == SPECIAL_CATEGORY) { 
    predictCashback  += purchase.amound * specialPurchasesPercent; 
 } ;

**Comment by muhacc20** [comment]
if(purchase.category == REGULAR_CATEGORY) {
predictCashback += purchase.amound * regularPurchasesPercent;
} else
if (purchase.category == INCREASED_CATEGORY) {
predictCashback += purchase.amound * increasedPurchasesPercent;
} else
if (purchase.category == SPECIAL_CATEGORY) {
predictCashback += purchase.amound * specialPurchasesPercent;
} ;

@muhacc20
