### ISSUE TITLE
В готовом приложении должен быть только один способ, а не два

### ISSUE THREAD

**Issue by coursar** [muhacc20/hometask#4]
https://github.com/muhacc20/hometask/blob/16b25cbdd4a2067d0c9db9390a5f0c435079cc20/src/js/app.js#L59-L80

**Comment by muhacc20** [comment]
let cashback;

if(predictCashback > 3000){
    cashback = 3000;
} else if(predictCashback <= 3000){
    cashback = predictCashback
}

console.log( predictCashback);
console.log( cashback)

**Comment by coursar** [comment]
issue надо закрывать сообщениями коммита
